name: authing
version: 0.1.7
description: >-
  Authing dart sdk for flutter and dart Apps, you can gently auth to your App with Authing.
author: clearloop <udtrokia@163.com>
homepage: https://github.com/clearloop/authing.dart
documentation: https://authing.cn/graphiql/
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  meta: ^1.1.8
  encrypt: ^3.2.0
  graphql: ^2.0.0
  pointycastle: ^1.0.2
dev_dependencies:
  effective_dart: ^1.1.0
